excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://slmck.github.io
title: I Dig It
tagline: Artifacts, Archaeology and the Art of Digging Holes
description: A collection of interesting archaeological artifacts, research and experiences!
paginate: 3
