excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://slmck.github.io
title: Çatalhöyük School Kit Test Site
tagline: A Work in Progress
description: Developing Pre-Historic Empathy through Chatbot Facilitated Discussion
paginate: 1

