excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://slmck.github.io
title: I Dig It
tagline: Totally Rad Archaeology Dude!
description: A collection of interesting archaeological artifacts, research and experiences!
paginate: 5
