excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://slmck.github.io
title: Çatalhöyük School Kit 
tagline: An Egalitarian Experience 
description: The Çatalhöyük School Kit is an EMOTIVE initiative which explores the egalitarian society of Çatalhöyük. Instructions and additional information can be found below.  
paginate: 1

