excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://slmck.github.io
title: Exploration of Egalitarianism 
tagline: A Digital Education Kit 
description: The Digital Education Kit is an EMOTIVE initiative which explores the egalitarian society of Çatalhöyük. Instructions and additional information can be found below.  
paginate: 1

