excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://slmck.github.io
title: Çatalhöyük School Kit 
tagline: An Egalitarian Experience 
description: An EMOTIVE initiative. 
paginate: 1

