excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://slmck.github.io
title: Çatalhöyük School Kit Test Site
tagline: Developing Pre-Historic Empathy through Chatbot Facilitated Discussion
description: A Work in Progress
paginate: 1

Artifacts, Archaeology and the Art of Digging Holes
A collection of interesting archaeological artifacts, research and experiences!
